export const PDF_LIST_REQUEST = 'pdf-list-request'
export const PDF_LIST_RESPONSE = 'pdf-list-response'
export const START_ANALYSIS_REQUEST = 'start-analyzis-request'
export const STOP_ANALYSIS_REQUEST = 'stop-analyzis-response'
export const UPDATE_PROGRESS_RESPONSE = 'update-progress-response'
export const UPDATE_REPORT_RESPONSE = 'update-report-response'
